//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Station1_Client.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoapBinding", Namespace="http://service")]
    public partial class ServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback searchCarOperationCompleted;
        
        private System.Threading.SendOrPostCallback stationTwoRegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback stationOneRegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback productRegistrationOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertProductPartOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceService() {
            this.Url = global::Station1_Client.Properties.Settings.Default.Station1_Client_WebReference_ServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event searchCarCompletedEventHandler searchCarCompleted;
        
        /// <remarks/>
        public event stationTwoRegisterCompletedEventHandler stationTwoRegisterCompleted;
        
        /// <remarks/>
        public event stationOneRegisterCompletedEventHandler stationOneRegisterCompleted;
        
        /// <remarks/>
        public event productRegistrationCompletedEventHandler productRegistrationCompleted;
        
        /// <remarks/>
        public event insertProductPartCompletedEventHandler insertProductPartCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("searchCarReturn")]
        public string[] searchCar(string vin) {
            object[] results = this.Invoke("searchCar", new object[] {
                        vin});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void searchCarAsync(string vin) {
            this.searchCarAsync(vin, null);
        }
        
        /// <remarks/>
        public void searchCarAsync(string vin, object userState) {
            if ((this.searchCarOperationCompleted == null)) {
                this.searchCarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchCarOperationCompleted);
            }
            this.InvokeAsync("searchCar", new object[] {
                        vin}, this.searchCarOperationCompleted, userState);
        }
        
        private void OnsearchCarOperationCompleted(object arg) {
            if ((this.searchCarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchCarCompleted(this, new searchCarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("stationTwoRegisterReturn")]
        public int stationTwoRegister(string partName, string partType, double weight, string vin, int palletID) {
            object[] results = this.Invoke("stationTwoRegister", new object[] {
                        partName,
                        partType,
                        weight,
                        vin,
                        palletID});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void stationTwoRegisterAsync(string partName, string partType, double weight, string vin, int palletID) {
            this.stationTwoRegisterAsync(partName, partType, weight, vin, palletID, null);
        }
        
        /// <remarks/>
        public void stationTwoRegisterAsync(string partName, string partType, double weight, string vin, int palletID, object userState) {
            if ((this.stationTwoRegisterOperationCompleted == null)) {
                this.stationTwoRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstationTwoRegisterOperationCompleted);
            }
            this.InvokeAsync("stationTwoRegister", new object[] {
                        partName,
                        partType,
                        weight,
                        vin,
                        palletID}, this.stationTwoRegisterOperationCompleted, userState);
        }
        
        private void OnstationTwoRegisterOperationCompleted(object arg) {
            if ((this.stationTwoRegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.stationTwoRegisterCompleted(this, new stationTwoRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("stationOneRegisterReturn")]
        public bool stationOneRegister(string vin, string model, string brand, int car_weight) {
            object[] results = this.Invoke("stationOneRegister", new object[] {
                        vin,
                        model,
                        brand,
                        car_weight});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void stationOneRegisterAsync(string vin, string model, string brand, int car_weight) {
            this.stationOneRegisterAsync(vin, model, brand, car_weight, null);
        }
        
        /// <remarks/>
        public void stationOneRegisterAsync(string vin, string model, string brand, int car_weight, object userState) {
            if ((this.stationOneRegisterOperationCompleted == null)) {
                this.stationOneRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstationOneRegisterOperationCompleted);
            }
            this.InvokeAsync("stationOneRegister", new object[] {
                        vin,
                        model,
                        brand,
                        car_weight}, this.stationOneRegisterOperationCompleted, userState);
        }
        
        private void OnstationOneRegisterOperationCompleted(object arg) {
            if ((this.stationOneRegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.stationOneRegisterCompleted(this, new stationOneRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("productRegistrationReturn")]
        public int productRegistration(string productName, string type, string destination) {
            object[] results = this.Invoke("productRegistration", new object[] {
                        productName,
                        type,
                        destination});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void productRegistrationAsync(string productName, string type, string destination) {
            this.productRegistrationAsync(productName, type, destination, null);
        }
        
        /// <remarks/>
        public void productRegistrationAsync(string productName, string type, string destination, object userState) {
            if ((this.productRegistrationOperationCompleted == null)) {
                this.productRegistrationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnproductRegistrationOperationCompleted);
            }
            this.InvokeAsync("productRegistration", new object[] {
                        productName,
                        type,
                        destination}, this.productRegistrationOperationCompleted, userState);
        }
        
        private void OnproductRegistrationOperationCompleted(object arg) {
            if ((this.productRegistrationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.productRegistrationCompleted(this, new productRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service", ResponseNamespace="http://service", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("insertProductPartReturn")]
        public bool insertProductPart(int productID, int partID) {
            object[] results = this.Invoke("insertProductPart", new object[] {
                        productID,
                        partID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void insertProductPartAsync(int productID, int partID) {
            this.insertProductPartAsync(productID, partID, null);
        }
        
        /// <remarks/>
        public void insertProductPartAsync(int productID, int partID, object userState) {
            if ((this.insertProductPartOperationCompleted == null)) {
                this.insertProductPartOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertProductPartOperationCompleted);
            }
            this.InvokeAsync("insertProductPart", new object[] {
                        productID,
                        partID}, this.insertProductPartOperationCompleted, userState);
        }
        
        private void OninsertProductPartOperationCompleted(object arg) {
            if ((this.insertProductPartCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertProductPartCompleted(this, new insertProductPartCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void searchCarCompletedEventHandler(object sender, searchCarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchCarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchCarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void stationTwoRegisterCompletedEventHandler(object sender, stationTwoRegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class stationTwoRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal stationTwoRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void stationOneRegisterCompletedEventHandler(object sender, stationOneRegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class stationOneRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal stationOneRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void productRegistrationCompletedEventHandler(object sender, productRegistrationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class productRegistrationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal productRegistrationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void insertProductPartCompletedEventHandler(object sender, insertProductPartCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertProductPartCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertProductPartCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591